object Form1: TForm1
  Left = 307
  Top = 54
  Width = 406
  Height = 620
  Caption = 'Form1'
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'MS Sans Serif'
  Font.Style = []
  OldCreateOrder = False
  PixelsPerInch = 96
  TextHeight = 13
  object EditDisplay: TEdit
    Left = 16
    Top = 0
    Width = 345
    Height = 48
    Font.Charset = ANSI_CHARSET
    Font.Color = clWindowText
    Font.Height = -33
    Font.Name = 'Calibri'
    Font.Style = [fsBold]
    ParentFont = False
    TabOrder = 0
    Text = '0'
  end
  object btn4: TButton
    Left = 8
    Top = 296
    Width = 81
    Height = 81
    Caption = '4'
    Font.Charset = ANSI_CHARSET
    Font.Color = clWindowText
    Font.Height = -48
    Font.Name = 'Calibri'
    Font.Style = [fsBold]
    ParentFont = False
    TabOrder = 1
    OnClick = NumberClick
  end
  object btn5: TButton
    Left = 104
    Top = 296
    Width = 81
    Height = 81
    Caption = '5'
    Font.Charset = ANSI_CHARSET
    Font.Color = clWindowText
    Font.Height = -48
    Font.Name = 'Calibri'
    Font.Style = [fsBold]
    ParentFont = False
    TabOrder = 2
    OnClick = NumberClick
  end
  object btn6: TButton
    Left = 200
    Top = 296
    Width = 81
    Height = 81
    Caption = '6'
    Font.Charset = ANSI_CHARSET
    Font.Color = clWindowText
    Font.Height = -48
    Font.Name = 'Calibri'
    Font.Style = [fsBold]
    ParentFont = False
    TabOrder = 3
    OnClick = NumberClick
  end
  object btnSub: TButton
    Left = 296
    Top = 296
    Width = 81
    Height = 81
    Caption = '-'
    Font.Charset = ANSI_CHARSET
    Font.Color = clWindowText
    Font.Height = -48
    Font.Name = 'Calibri'
    Font.Style = [fsBold]
    ParentFont = False
    TabOrder = 4
    OnClick = OperatorClick
  end
  object btn1: TButton
    Left = 8
    Top = 392
    Width = 81
    Height = 81
    Caption = '1'
    Font.Charset = ANSI_CHARSET
    Font.Color = clWindowText
    Font.Height = -48
    Font.Name = 'Calibri'
    Font.Style = [fsBold]
    ParentFont = False
    TabOrder = 5
    OnClick = NumberClick
  end
  object btn2: TButton
    Left = 104
    Top = 392
    Width = 81
    Height = 81
    Caption = '2'
    Font.Charset = ANSI_CHARSET
    Font.Color = clWindowText
    Font.Height = -48
    Font.Name = 'Calibri'
    Font.Style = [fsBold]
    ParentFont = False
    TabOrder = 6
    OnClick = NumberClick
  end
  object btn3: TButton
    Left = 200
    Top = 392
    Width = 81
    Height = 81
    Caption = '3'
    Font.Charset = ANSI_CHARSET
    Font.Color = clWindowText
    Font.Height = -48
    Font.Name = 'Calibri'
    Font.Style = [fsBold]
    ParentFont = False
    TabOrder = 7
    OnClick = NumberClick
  end
  object btnMult: TButton
    Left = 296
    Top = 392
    Width = 81
    Height = 81
    Caption = '*'
    Font.Charset = ANSI_CHARSET
    Font.Color = clWindowText
    Font.Height = -48
    Font.Name = 'Calibri'
    Font.Style = [fsBold]
    ParentFont = False
    TabOrder = 8
    OnClick = OperatorClick
  end
  object btnBS: TButton
    Left = 8
    Top = 104
    Width = 81
    Height = 81
    Caption = 'X'
    Font.Charset = ANSI_CHARSET
    Font.Color = clWindowText
    Font.Height = -48
    Font.Name = 'Calibri'
    Font.Style = [fsBold]
    ParentFont = False
    TabOrder = 9
    OnClick = btnBSClick
  end
  object btnCE: TButton
    Left = 104
    Top = 104
    Width = 81
    Height = 81
    Caption = 'CE'
    Font.Charset = ANSI_CHARSET
    Font.Color = clWindowText
    Font.Height = -48
    Font.Name = 'Calibri'
    Font.Style = [fsBold]
    ParentFont = False
    TabOrder = 10
    OnClick = btnCEClick
  end
  object btnC: TButton
    Left = 200
    Top = 104
    Width = 81
    Height = 81
    Caption = 'C'
    Font.Charset = ANSI_CHARSET
    Font.Color = clWindowText
    Font.Height = -48
    Font.Name = 'Calibri'
    Font.Style = [fsBold]
    ParentFont = False
    TabOrder = 11
    OnClick = btnCClick
  end
  object btnPM: TButton
    Left = 296
    Top = 104
    Width = 81
    Height = 81
    Caption = #177
    Font.Charset = ANSI_CHARSET
    Font.Color = clWindowText
    Font.Height = -48
    Font.Name = 'Calibri'
    Font.Style = [fsBold]
    ParentFont = False
    TabOrder = 12
    OnClick = btnPMClick
  end
  object btn9: TButton
    Left = 8
    Top = 200
    Width = 81
    Height = 81
    Caption = '9'
    Font.Charset = ANSI_CHARSET
    Font.Color = clWindowText
    Font.Height = -48
    Font.Name = 'Calibri'
    Font.Style = [fsBold]
    ParentFont = False
    TabOrder = 13
    OnClick = NumberClick
  end
  object btn8: TButton
    Left = 104
    Top = 200
    Width = 81
    Height = 81
    Caption = '8'
    Font.Charset = ANSI_CHARSET
    Font.Color = clWindowText
    Font.Height = -48
    Font.Name = 'Calibri'
    Font.Style = [fsBold]
    ParentFont = False
    TabOrder = 14
    OnClick = NumberClick
  end
  object btn7: TButton
    Left = 200
    Top = 200
    Width = 81
    Height = 81
    Caption = '7'
    Font.Charset = ANSI_CHARSET
    Font.Color = clWindowText
    Font.Height = -48
    Font.Name = 'Calibri'
    Font.Style = [fsBold]
    ParentFont = False
    TabOrder = 15
    OnClick = NumberClick
  end
  object btnAdd: TButton
    Left = 296
    Top = 200
    Width = 81
    Height = 81
    Caption = '+'
    Font.Charset = ANSI_CHARSET
    Font.Color = clWindowText
    Font.Height = -48
    Font.Name = 'Calibri'
    Font.Style = [fsBold]
    ParentFont = False
    TabOrder = 16
    OnClick = OperatorClick
  end
  object btn0: TButton
    Left = 8
    Top = 488
    Width = 81
    Height = 81
    Caption = '0'
    Font.Charset = ANSI_CHARSET
    Font.Color = clWindowText
    Font.Height = -48
    Font.Name = 'Calibri'
    Font.Style = [fsBold]
    ParentFont = False
    TabOrder = 17
    OnClick = NumberClick
  end
  object btnDot: TButton
    Left = 104
    Top = 488
    Width = 81
    Height = 81
    Caption = '.'
    Font.Charset = ANSI_CHARSET
    Font.Color = clWindowText
    Font.Height = -48
    Font.Name = 'Calibri'
    Font.Style = [fsBold]
    ParentFont = False
    TabOrder = 18
    OnClick = btnDotClick
  end
  object btnEquals: TButton
    Left = 200
    Top = 488
    Width = 81
    Height = 81
    Caption = '='
    Font.Charset = ANSI_CHARSET
    Font.Color = clWindowText
    Font.Height = -48
    Font.Name = 'Calibri'
    Font.Style = [fsBold]
    ParentFont = False
    TabOrder = 19
    OnClick = btnEqualsClick
  end
  object btnDiv: TButton
    Left = 296
    Top = 488
    Width = 81
    Height = 81
    Caption = '/'
    Font.Charset = ANSI_CHARSET
    Font.Color = clWindowText
    Font.Height = -48
    Font.Name = 'Calibri'
    Font.Style = [fsBold]
    ParentFont = False
    TabOrder = 20
    OnClick = OperatorClick
  end
  object Edit: TEdit
    Left = 16
    Top = 48
    Width = 345
    Height = 48
    Font.Charset = ANSI_CHARSET
    Font.Color = clWindowText
    Font.Height = -33
    Font.Name = 'Calibri'
    Font.Style = [fsBold]
    ParentFont = False
    TabOrder = 21
    Text = '0'
  end
end
